repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://$(pwd) --since_commit HEAD --no-verification --no-update --fail'
        language: system
        stages: ["pre-commit", "pre-push"]